---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common utilities
  apt:
    name:
      - curl
      - htop
      - git
      - unzip
    state: present

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: yes
